apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: food-truck
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: registry-vpc.cn-shanghai.aliyuncs.com/food-truck-acr/api-gateway:${IMAGE-TAG}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: food-truck
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
    