FROM openjdk:17.0.1-jdk
ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai
ADD target/food-service.jar   app.jar

CMD ["sh","-c","java -Xmx512m -Xms256m -XX:SurvivorRatio=4 -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -jar -XX:InitiatingHeapOccupancyPercent=70    app.jar --spring.profiles.active=dev"]